"""
Module for building an Abstract Syntax Tree (AST) from a parse tree using Lark.
"""

from typing import Any, Callable, List

from lark import Token, Transformer

from app.core.language.ast.node import (AddEdgeFunction, AddNodeFunction,
                                        ArrayAccess, ArraySlice, ArrayTarget,
                                        ArrayVarDecl, Assignment, ASTNode,
                                        BinOp, Bool, CallMethod, CallStmt,
                                        CeilFunction, ClassDef, ConcatFunction,
                                        FieldAccess, FieldTarget,
                                        FloorFunction, ForLoop, FuncCallExpr,
                                        GraphOperation, GraphTraversal,
                                        GraphVarDecl, IfElse, LengthFunction,
                                        NeighborsFunction, NewGraph, NewObject,
                                        Null, Number, ObjectVarDecl, Parameter,
                                        PrintStmt, Program, RepeatUntil,
                                        ReturnStmt, ShortCircuitBinOp, String,
                                        StrlenFunction, SubroutineDef,
                                        SubstringFunction, UnOp, Var, VarDecl,
                                        VarTarget, WhileLoop)
from app.core.utils import (ArrayDimensionTracker, ASTNormalizer,
                            BinaryOperationHandler, IndexerProcessor,
                            MultidimensionalArrayHandler, ParameterProcessor,
                            TokenExtractor)


class ASTBuilder(Transformer):
    """
    Builds an Abstract Syntax Tree (AST) from a parse tree generated by Lark.
    Handles token normalization, binary operations, parameters, and multidimensional arrays.
    """

    def __init__(self):
        super().__init__()

        self._token_extractor = TokenExtractor()
        self._indexer_processor = IndexerProcessor()
        self._dimension_tracker = ArrayDimensionTracker()
        self._multidimensional_handler = MultidimensionalArrayHandler(
            self._dimension_tracker
        )

        self._normalizer = ASTNormalizer(self)
        self._binary_handler = BinaryOperationHandler(self._normalizer)
        self._parameter_processor = ParameterProcessor(self._token_extractor)

        self._setup_token_handlers()

    def _setup_token_handlers(self):
        """
        Set up token handlers for AST construction. Ignores certain tokens and maps others to AST nodes.
        """
        tokens_ignore = {
            "ASSIGN",
            "FOR",
            "TO",
            "DO",
            "BEGIN",
            "END",
            "RANGE",
            "CALL_KW",
            "RETURN_KW",
            "CLASS_KW",
            "VAR_KW",
            "NEW_KW",
            "LENGTH_KW",
            "CEIL",
            "FLOOR",
            "CONCAT",
            "SUBSTRING",
            "STRLEN",
            "GRAPH_KW",
            "NODE_KW",
            "EDGE_KW",
            "ADDNODE",
            "ADDEDGE",
            "NEIGHBORS",
        }

        tokens_upper: dict[str, Callable[[Token], ASTNode]] = {
            "STRING": lambda tok: String(value=tok.value[1:-1]),
            "VAR": lambda tok: Var(name=tok.value),
            "TRUE": lambda _: Bool(True),
            "FALSE": lambda _: Bool(False),
            "NULL": lambda _: Null(),
            "NUMBER": lambda tok: Number(
                value=float(tok.value) if "." in tok.value else int(tok.value)
            ),
        }

        for tok in tokens_ignore:
            if hasattr(self, tok):
                delattr(self, tok)

        for k, v in tokens_upper.items():
            setattr(self, k, v)

    def transform(self, tree: Any) -> Program:
        """
        Transform the parse tree into an AST and normalize it.
        """
        ast = super().transform(tree)
        return self._normalizer.normalize(ast)

    def program(self, items: List[Any]) -> Program:
        """ """
        statements = self._flatten_and_filter(items)
        return Program(statements=statements)

    def _flatten_and_filter(self, items: List[Any]) -> List[ASTNode]:
        """
        Flatten nested lists and filter out Null and Token instances.
        """
        result: List[ASTNode] = []
        for item in items:
            if isinstance(item, (Null, Token)):
                continue
            if isinstance(item, list):
                result.extend(self._flatten_and_filter(item))
            else:
                result.append(item)
        return result

    def var(self, items: List[Any]) -> Var:
        if items and isinstance(items[0], Token) and items[0].type == "VAR":
            return Var(name=items[0].value)
        if items and isinstance(items[0], Var):
            return items[0]
        return Var(name="")

    def number(self, items: List[Any]) -> Number:
        if items and isinstance(items[0], Token) and items[0].type == "NUMBER":
            s = items[0].value
            return Number(value=float(s) if "." in s else int(s))
        if items and isinstance(items[0], Number):
            return items[0]
        return Number(value=0)

    def string(self, items: List[Any]) -> String:
        if items and isinstance(items[0], Token) and items[0].type == "STRING":
            return String(value=items[0].value[1:-1])
        if items and isinstance(items[0], String):
            return items[0]
        return String(value="")

    def var_decl_item(self, items: List[Any]) -> tuple[str, Any]:
        name = self._token_extractor.extract_name(items[0])
        return (name, items[1] if len(items) > 1 else Null())

    def var_decl(self, items: List[Any]) -> VarDecl:
        items2: List[Any] = [it for it in items if not isinstance(it, Token)]
        return VarDecl(items=items2)

    def lvalue_var(self, items: List[Any]) -> VarTarget:
        return VarTarget(name=self._token_extractor.extract_name(items[0]))

    def lvalue_field(self, items: List[Any]) -> FieldTarget:
        return FieldTarget(
            obj=self._token_extractor.extract_name(items[0]),
            field=self._token_extractor.extract_name(items[1]),
        )

    def assignment(self, items: List[Any]) -> Assignment:
        if not items:
            return Assignment(target=Null(), value=Null())

        raw_target = items[0]
        value = items[-1] if len(items) > 1 else Null()

        if isinstance(raw_target, Var):
            target = VarTarget(name=raw_target.name)
        elif isinstance(raw_target, list) and len(raw_target) == 2:
            if all(isinstance(x, Var) for x in raw_target):
                target = FieldTarget(obj=raw_target[0].name, field=raw_target[1].name)
            else:
                target = raw_target
        else:
            target = raw_target

        return Assignment(target=target, value=value)

    def for_loop(self, items: List[Any]) -> ForLoop:
        var_name = self._token_extractor.extract_name(items[1])
        start_expr = self._normalizer.normalize(items[3])
        end_expr = self._normalizer.normalize(items[5])
        body = self._normalizer.normalize(items[7])

        return ForLoop(
            var=var_name,
            start=start_expr,
            end=end_expr,
            body=body,
            preserve_counter_value=True,
        )

    def while_loop(self, items: List[Any]) -> WhileLoop:
        cond = self._normalizer.normalize(items[1])
        body = self._normalizer.normalize(items[3])

        return WhileLoop(cond=cond, body=body)

    def repeat_loop(self, items: List[Any]) -> RepeatUntil:
        until_index = next(
            (
                i
                for i, item in enumerate(items)
                if isinstance(item, Token) and item.type == "UNTIL"
            ),
            -1,
        )

        if until_index == -1:
            body = self._normalizer.normalize(items[1:]) if len(items) > 1 else []
            return RepeatUntil(body=body, cond=Null())

        body = self._normalizer.normalize(items[1:until_index])
        cond = self._normalizer.normalize(items[until_index + 1])

        return RepeatUntil(body=body, cond=cond)

    def if_statement(self, items: List[Any]) -> IfElse:
        cond = items[1]
        then_branch = items[3]
        else_branch = []

        try:
            else_index = items.index("else")
            else_branch = items[else_index + 1]
        except ValueError:
            pass

        return IfElse(cond=cond, then_branch=then_branch, else_branch=else_branch)

    def call_stmt(self, items: List[Any]) -> CallStmt:
        name = self._token_extractor.extract_name(items[1])
        args = items[2:]
        return CallStmt(name=name, args=args)

    def return_stmt(self, items: List[Any]) -> ReturnStmt:
        return ReturnStmt(value=items[1] if len(items) > 1 else Null())

    def class_def(self, items: List[Any]) -> ClassDef:
        name = None
        fields: List[str] = []

        for it in items:
            if isinstance(it, Token) and (
                it.type == "CLASS_KW" or it.value in ["{", "}"]
            ):
                continue
            if not name:
                name = self._token_extractor.extract_name(it)
            else:
                field_name = self._token_extractor.extract_name(it)
                if field_name:
                    fields.append(field_name)

        return ClassDef(name=name or Null(), fields=fields)

    def sum(self, items: List[Any]) -> Any:
        return self._binary_handler.process_chain(items)

    def product(self, items: List[Any]) -> Any:
        return self._binary_handler.process_chain(items)

    def add(self, items: List[Any]) -> Any:
        return self._binary_handler.create_binary_operation("+", items[0], items[2])

    def sub(self, items: List[Any]) -> Any:
        return self._binary_handler.create_binary_operation("-", items[0], items[2])

    def mul(self, items: List[Any]) -> Any:
        left = items[0]
        right = items[2] if len(items) > 2 else items[1]
        return self._binary_handler.create_binary_operation("*", left, right)

    def div(self, items: List[Any]) -> Any:
        left = items[0]
        right = items[2] if len(items) > 2 else items[1]
        return self._binary_handler.create_binary_operation("/", left, right)

    def mod(self, items: List[Any]) -> Any:
        left = items[0]
        right = items[2] if len(items) > 2 else items[1]
        return self._binary_handler.create_binary_operation("mod", left, right)

    def divint(self, items: List[Any]) -> Any:
        left = items[0]
        right = items[2] if len(items) > 2 else items[1]
        return self._binary_handler.create_binary_operation("div", left, right)

    def or_expr(self, items: List[Any]) -> Any:
        if len(items) == 1:
            return items[0]

        left = items[0]
        i = 1
        while i < len(items):
            if i + 1 < len(items):
                right = items[i + 1]
                left = ShortCircuitBinOp("or", left, right)
                i += 2
            else:
                i += 1
        return left

    def and_expr(self, items: List[Any]) -> Any:
        if len(items) == 1:
            return items[0]

        left = items[0]
        i = 1
        while i < len(items):
            if i + 1 < len(items):
                right = items[i + 1]
                left = ShortCircuitBinOp("and", left, right)
                i += 2
            else:
                i += 1
        return left

    def not_expr(self, items: List[Any]) -> Any:
        if len(items) == 1:
            return items[0]
        return UnOp("not", items[-1])

    def comp_expr(self, items: List[Any]) -> Any:
        if len(items) == 1:
            return items[0]

        left = items[0]
        op = items[1]
        right = items[2]
        op_str = op.value if hasattr(op, "value") else str(op)

        return BinOp(op_str, left, right)

    def simple_parameter(self, items):
        name = self._token_extractor.extract_name(items[0]) if items else ""
        return Parameter(name=name, param_type="var", dimensions=None, class_name=None)

    def array_parameter(self, items):
        name = self._token_extractor.extract_name(items[0]) if items else ""
        dimensions = []

        for item in items[1:]:
            if item is None:
                dimensions.append(None)
            elif isinstance(item, list):
                dimensions.extend(item)
            elif item and not isinstance(item, Token):
                dimensions.append(item)

        return Parameter(
            name=name, param_type="array", dimensions=dimensions, class_name=None
        )

    def object_parameter(self, items):
        if len(items) < 3:
            return Parameter(
                name="", param_type="object", dimensions=None, class_name=""
            )
        class_name = self._token_extractor.extract_name(items[1])
        var_name = self._token_extractor.extract_name(items[2])
        return Parameter(
            name=var_name, param_type="object", dimensions=None, class_name=class_name
        )

    def graph_parameter(self, items):
        name = self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
        return Parameter(
            name=name, param_type="graph", dimensions=None, class_name=None
        )

    def code_block(self, items: List[Any]) -> List[ASTNode]:
        return self._flatten_and_filter(items)

    def atom(self, items: List[Any]) -> Any:
        if not items:
            return Null()

        if isinstance(items[0], ASTNode):
            return items[0]

        if isinstance(items[0], Token):
            token = items[0]
            token_type = {"NUMBER", "STRING", "VAR", "TRUE", "FALSE", "NULL"}

            if token.type in token_type:
                return getattr(self, token.type.lower())([token])

        return items[0]

    def length_function(self, items: List[Any]) -> LengthFunction:
        array_expr = items[1] if len(items) > 1 else Null()
        return LengthFunction(array=array_expr)

    def ceil_function(self, items: List[Any]) -> CeilFunction:
        expr = items[1] if len(items) > 1 else Null()
        return CeilFunction(expr=expr)

    def floor_function(self, items: List[Any]) -> FloorFunction:
        expr = items[1] if len(items) > 1 else Null()
        return FloorFunction(expr=expr)

    def concat_function(self, items: List[Any]) -> ConcatFunction:
        left = items[1] if len(items) > 1 else Null()
        right = items[2] if len(items) > 2 else Null()
        return ConcatFunction(left=left, right=right)

    def substring_function(self, items: List[Any]) -> SubstringFunction:
        string = items[1] if len(items) > 1 else Null()
        start = items[2] if len(items) > 2 else Null()
        length = items[3] if len(items) > 3 else Null()
        return SubstringFunction(string=string, start=start, length=length)

    def strlen_function(self, items: List[Any]) -> StrlenFunction:
        expr = items[1] if len(items) > 1 else Null()
        return StrlenFunction(expr=expr)

    def func_call_expr(self, items: List[Any]) -> FuncCallExpr:
        """
        Handles function calls with or without the CALL keyword.
        """
        if not items:
            return FuncCallExpr(name=Null(), args=[])

        first_item = items[0]
        if isinstance(first_item, Token) and first_item.type == "CALL_KW":
            name = (
                self._token_extractor.extract_name(items[1])
                if len(items) > 1
                else Null()
            )
            args = items[2:] if len(items) > 2 else []
        elif first_item is Null() or (
            isinstance(first_item, Token) and first_item.type == "CALL_KW"
        ):
            name = (
                self._token_extractor.extract_name(items[1])
                if len(items) > 1
                else Null()
            )
            args = items[2:] if len(items) > 2 else []
        else:
            name = self._token_extractor.extract_name(items[0])
            args = items[1:] if len(items) > 1 else []

        return FuncCallExpr(name=name, args=args)

    def call_method(self, items: List[Any]) -> CallMethod:
        obj = self._token_extractor.extract_name(items[0]) if items else ""
        method = self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
        args = items[2:] if len(items) > 2 else []
        return CallMethod(obj=obj, method=method, args=args)

    def new_object(self, items: List[Any]) -> NewObject:
        cname = self._token_extractor.extract_name(items[1]) if items else ""
        return NewObject(class_name=cname)

    def array_access(self, items) -> ArrayAccess:
        name = self._token_extractor.extract_name(items[0])
        raw_idxs = (
            items[1]
            if len(items) > 1 and isinstance(items[1], list)
            else items[1:] if len(items) > 1 else []
        )
        idxs = raw_idxs
        return self._multidimensional_handler.create_enhanced_array_access(name, idxs)

    def lvalue_array(self, items):
        name = self._token_extractor.extract_name(items[0])
        raw_idxs = (
            items[1]
            if len(items) > 1 and isinstance(items[1], list)
            else items[1:] if len(items) > 1 else []
        )
        idxs = raw_idxs
        return ArrayTarget(name=name, index=idxs)

    def array_slice(self, items) -> ArraySlice:
        name = self._token_extractor.extract_name(items[0])

        if len(items) == 4 and str(items[2]) == "..":
            start = items[1]
            end = items[3]
            ranges = [(start, end)]
        else:
            raw_inner = (
                items[1]
                if len(items) > 1 and isinstance(items[1], list)
                else items[1:] if len(items) > 1 else []
            )
            ranges = []
            for entry in raw_inner:
                if isinstance(entry, tuple):
                    ranges.append(entry)
                else:
                    ranges.append((entry, entry))

        return self._multidimensional_handler.create_enhanced_array_slice(name, ranges)

    def array_var_decl(self, items):
        name = self._token_extractor.extract_name(items[0]) if items else ""
        dims = items[1] if len(items) > 1 and isinstance(items[1], list) else items[1:]
        dimensions = list(dims)

        self._dimension_tracker.register_array(name, dimensions)
        return ArrayVarDecl(name=name, dimensions=dimensions)

    def indexer_range(self, items):
        filtered = [item for item in items if not isinstance(item, Token)]
        if len(filtered) >= 2:
            return (filtered[0], filtered[1])

        if len(filtered) == 1:
            return (filtered[0], filtered[0])
        return (Null(), Null())

    def indexer_open_start(self, items):
        filtered = [item for item in items if not isinstance(item, Token)]
        return (Null(), filtered[0]) if filtered else (Null(), Null())

    def indexer_open_end(self, items):
        filtered = [item for item in items if not isinstance(item, Token)]
        return (filtered[0], Null()) if filtered else (Null(), Null())

    def indexer_open_both(self, _):
        return (Null(), Null())

    def indexer_single(self, items):
        return items[0] if items else Null()

    def indexer_empty(self, _):
        """Handle empty brackets [] in array parameters"""
        return None

    def field_access(self, items: List[Any]) -> FieldAccess:
        obj = self._token_extractor.extract_name(items[0])
        field = self._token_extractor.extract_name(items[1])
        return FieldAccess(obj=obj, field=field)

    def subroutine_def(self, items: List[Token]) -> SubroutineDef:
        name = self._token_extractor.extract_name(items[0]) if items else Null()
        params: List[Any] = []
        body: List[Any] = []

        for it in items[1:]:
            if isinstance(it, list):
                if it and all(isinstance(x, Parameter) for x in it):
                    params.extend(it)
                else:
                    body = it
            elif isinstance(it, Parameter):
                params.append(it)

        return SubroutineDef(name=name, parameters=params, body=body)

    def object_var_decl(self, items: List[Any]) -> ObjectVarDecl:
        if len(items) < 3:
            cls = self._token_extractor.extract_name(items[0]) if items else ""
            name = (
                self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
            )
        else:
            cls = self._token_extractor.extract_name(items[1])
            name = self._token_extractor.extract_name(items[2])
        return ObjectVarDecl(class_name=cls, name=name)

    def graph_traversal(self, items: List[Any]) -> GraphTraversal:
        graph = self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
        start_node = items[2] if len(items) > 2 else Null()
        end_node = items[3] if len(items) > 3 else Null()
        return GraphTraversal(graph=graph, start_node=start_node, end_node=end_node)

    def graph_operation(self, items: List[Any]) -> GraphOperation:
        graph = self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
        nodes = items[2:] if len(items) > 2 else []
        return GraphOperation(graph=graph, nodes=nodes)

    def graph_var_decl(self, items: List[Any]) -> GraphVarDecl:
        name = self._token_extractor.extract_name(items[-1]) if items else ""
        return GraphVarDecl(name=name)

    def new_graph(self, _: List[Any]) -> NewGraph:
        return NewGraph()

    def addnode_function(self, items: List[Any]) -> AddNodeFunction:
        graph = self._token_extractor.extract_name(items[0]) if len(items) > 0 else ""
        node = items[1] if len(items) > 1 else Null()
        return AddNodeFunction(graph=graph, node=node)

    def addnode_stmt(self, items: List[Any]) -> AddNodeFunction:
        graph = self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
        node = items[2] if len(items) > 2 else Null()
        return AddNodeFunction(graph=graph, node=node)

    def addedge_function(self, items: List[Any]) -> AddEdgeFunction:
        graph = self._token_extractor.extract_name(items[0]) if len(items) > 0 else ""
        from_node = items[1] if len(items) > 1 else Null()
        to_node = items[2] if len(items) > 2 else Null()
        return AddEdgeFunction(graph=graph, from_node=from_node, to_node=to_node)

    def addedge_stmt(self, items: List[Any]) -> AddEdgeFunction:
        graph = self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
        from_node = items[2] if len(items) > 2 else Null()
        to_node = items[3] if len(items) > 3 else Null()
        return AddEdgeFunction(graph=graph, from_node=from_node, to_node=to_node)

    def neighbors_function(self, items: List[Any]) -> NeighborsFunction:
        graph = self._token_extractor.extract_name(items[1]) if len(items) > 1 else ""
        node = items[2] if len(items) > 2 else Null()
        return NeighborsFunction(graph=graph, node=node)

    def print_stmt(self, items: List[Any]) -> PrintStmt:
        value = items[1] if len(items) > 1 else Null()
        return PrintStmt(value=value)
