"""
Module for building the AST from the parse tree generated by Lark.
"""
from typing import Any
from lark import Transformer


class ASTBuilder(Transformer[Any]):
    """
    Builds an Abstract Syntax Tree (AST) from a parse tree generated by Lark.
    Handles token normalization, binary operations, parameters, and multidimensional arrays.
    """

    def __init__(self):
        pass