"""Helpers to persist pipeline artifacts such as AST dumps or recursion trees."""

import hashlib
import json
from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import Any, Dict, Optional

from app.core.constants import DATA_DIR
from app.core.language.ast import Program


class ArtifactManager:
    """Persists intermediate artifacts generated by the pipeline."""

    def __init__(self, base_dir: str = DATA_DIR):
        self.base_path = Path(base_dir) / "artifacts"
        self.ast_path = self.base_path / "asts"
        self.recursion_tree_path = self.base_path / "recursion_trees"
        self.logs_path = self.base_path / "logs"

        for folder in (self.ast_path, self.recursion_tree_path, self.logs_path):
            folder.mkdir(parents=True, exist_ok=True)

    def persist_ast(self, program: Program, pseudocode: str) -> Dict[str, str]:
        """Dump the AST to disk and return its identifiers."""
        digest = hashlib.sha256(pseudocode.encode("utf-8")).hexdigest()
        target = self.ast_path / f"{digest}.json"
        if not target.exists():
            data = self._serialize(program)
            target.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return {"digest": digest, "path": str(target)}

    def persist_recursion_tree(self, tree_text: str, pseudocode: str) -> Optional[str]:
        """Persist recursion tree visualization (if any)."""
        if not tree_text:
            return None
        digest = hashlib.sha256((pseudocode + tree_text).encode("utf-8")).hexdigest()
        target = self.recursion_tree_path / f"{digest}.txt"
        target.write_text(tree_text, encoding="utf-8")
        return str(target)

    def persist_log(self, name: str, content: str) -> str:
        target = self.logs_path / f"{name}.log"
        target.write_text(content, encoding="utf-8")
        return str(target)

    def _serialize(self, node: Any) -> Any:
        if is_dataclass(node):
            return asdict(node)
        if isinstance(node, list):
            return [self._serialize(item) for item in node]
        if isinstance(node, dict):
            return {k: self._serialize(v) for k, v in node.items()}
        return node
